### ISSUE TITLE
Build error: no such file or directory: '~/V2EX/Wear/Wear/Extensions/

### ISSUE THREAD

**Issue by litt1e-p** [Joe0708/V2EX#1]
@Joe0708 hi, I get an error `error: no such file or directory: '~/V2EX/Wear/Wear/Extensions/*` when build the [V2EX](https://github.com/Joe0708/V2EX), do I miss some files?
My Environment: Xcode9.1, Swift4. Thanks!

**Comment by Joe0708** [comment]
@litt1e-p Sorry, the file reference error has been repaired. Please update the code to retry.

**Comment by litt1e-p** [comment]
@Joe0708  I get some new errors now
![](http://ww2.sinaimg.cn/large/006tNc79gy1fl9bdjsp2fj30i00padlr.jpg)

**Comment by Joe0708** [comment]
@litt1e-p Repaired. Please try again 😄

**Comment by litt1e-p** [comment]
@Joe0708 It works now🎉. Thanks a lot

**Comment by sauchye** [comment]
![image](https://user-images.githubusercontent.com/4171847/46450081-036f2a80-c7c2-11e8-92e1-7f15f6072fe8.png)
Hi, just clone your repo, but ``pod install``, If you have time, help me check, thank you ~
