### ISSUE TITLE
请问可否增加google登陆

### ISSUE THREAD

**Issue by ddqp** [Joe0708/V2EX#2]
目前没有任何一个V2客户端支持google登陆，这个很烦恼

**Comment by Joe0708** [comment]
这个我到时候可以尝试下能不能接入网页版，最近较忙😄

**Comment by ddqp** [comment]
好的，谢谢！

**Comment by ddqp** [comment]
已经申请TF，如果价格不是特别贵，必买

**Comment by Joe0708** [comment]
已经支持 Google 登录.
 你知道你邮箱哈, 给我发个邮箱, 邀请你内测, 现在是外部测试需要审核, 内测不需要审核

**Comment by Joe0708** [comment]
@ddqp 已经支持 Google 登录.
你知道你邮箱哈, 给我发个邮箱, 邀请你内测, 现在是外部测试需要审核, 内测不需要审核

**Comment by ddqp** [comment]
hello，已经在tf里面，谢谢啊

**Comment by ddqp** [comment]
不过没看到最新版本支持，可能还没推送吧？

**Comment by ddqp** [comment]
另外，做的真不错，挺喜欢的，就是希望增加一个沉浸模式：自动隐藏或者手动隐藏上下状态栏/功能栏
那样在iPhone x上很酷
