### ISSUE TITLE
希望支持钥匙串自动填充用户名密码

### ISSUE THREAD

**Issue by Grayon** [Joe0708/V2EX#5]
iOS 11 开放了新的 Password AutoFill SDK，体验很不错
目前版本虽然也可以调出钥匙串，但是需要自己选择站点，而且用户名和密码是单独填充，选择用户名输入框时自动填充只会填用户名，密码需要再选一次

**Comment by Joe0708** [comment]
该功能需要App和服务器双方配合验证，由于 App 非官方的，无法得到授权。需要官方配合才行。
很抱歉，目前来说无法做到。
[参考链接](https://code.tutsplus.com/articles/faster-logins-with-password-autofill-in-ios-11--cms-29096)
