### ISSUE TITLE
使用surge作者制作的规则，v2无法显示了

### ISSUE THREAD

**Issue by BAKAMiku** [Joe0708/V2EX#8]
主页面一直菊花转圈

**Comment by Joe0708** [comment]
@BAKAMiku 

任何规则和App本身没有任何关系, App是直接解析网页版数据.
网页版无法访问, App自然无法访问

另外, 从今天下午开始, 貌似 V站 一直处于无法访问状态, 估计挂了....
你可以通过浏览器查看是否能正常访问..

Thanks.
